<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://mcda5510.com" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://mcda5510.com" xmlns:intf="http://mcda5510.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:portType name="Assignment3">

   </wsdl:portType>

   <wsdl:binding name="Assignment3SoapBinding" type="impl:Assignment3">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

   </wsdl:binding>

   <wsdl:service name="Assignment3Service">

      <wsdl:port binding="impl:Assignment3SoapBinding" name="Assignment3">

         <wsdlsoap:address location="http://localhost:8080/Assignment3/services/Assignment3"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
